#服务提供方微服务配置
#server:
  #设置端口号
#  port:8070

#设置服务的名称
spring:
  application:
    name: login-server

#往eureka_service端注册的地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/